space-401/BackEnd

src/main/java/com/app/kkiri/config/OAuth2ClientConfig.java
src/main/java/com/app/kkiri/controller/LoginController.java
src/main/resources/static/index.html

🚀chore : 서버에 대한 인증 없는 접근 허용함

---

src/main/java/com/app/kkiri/common/CustomOAuth2AuthorizationRequestResolver.java
src/main/java/com/app/kkiri/controller/UserController.java

- 몇 개 class 의 package 명을 올바르게 수정했습니다.

📝fix : 일부 파일 package 명을 수정함

---

src/main/java/com/app/kkiri/controller/UserController.java

- UserController 의 oAuth2Login() 메서드의 매개변수를 수정했습니다.

📝fix : OAuth2 로그인을 위한 Controller 를 수정함

---

src/main/java/com/app/kkiri/config/SecurityConfig.java
src/main/resources/application.yml

- OAuth2 로그인 시 에러를 해결하기 위해 kakao client 의 client_secret 을 삭제했습니다.
- OAuth2 로그인 예외 발생 시 핸들러 클래스를 커스텀 핸들러에서 SimpleUrlAuthenticationHandler 클래스로 변경했습니다.

📝fix : OAuth2 로그인 시 에러를 해결하기 위해 kakao client 의 client_secret 을 삭제함

---

src/main/resources/application.yml

- kakao client 의 client_secret 을 추가했습니다.

📝fix : kakao client 의 client_secret 을 추가함.

---

.gitignore
build.gradle
src/main/java/com/app/kkiri/common/CustomOAuth2AuthorizationRequestResolver.java
src/main/java/com/app/kkiri/config/SecurityConfig.java
src/main/java/com/app/kkiri/myBatis/MyBatisConfig.java
src/main/resources/application.yml

- .gitignore 에 설정 파일을 제외하는 추가 코드를 작성했습니다.
- 빌드 시 테스트 코드를 빌드 하지 않도록 설정 코드를 작성했습니다.

📝fix : 배포 환경에서 빌드 에러 수정함

---

src/main/java/com/app/kkiri/security/SecurityConfig.java

- CORS 에러를 해결하기 위해 Acces-Control-Allow-Origin 속성값으로 "http://localhost:3000" 을 작성했습니다.

📝fix : CORS 에러 해결함

---

.idea/gradle.xml
src/main/java/com/app/kkiri/controller/CommentController.java
src/main/java/com/app/kkiri/controller/TestController.java
src/main/java/com/app/kkiri/domain/dto/UserDTO.java
src/main/java/com/app/kkiri/domain/dto/UserResponseDTO.java
src/main/java/com/app/kkiri/domain/vo/UserVO.java
src/main/java/com/app/kkiri/repository/UsersDAO.java
src/main/java/com/app/kkiri/security/SecurityConfig.java
src/main/java/com/app/kkiri/security/entryPoints/CustomAuthenticationEntryPoint.java
src/main/java/com/app/kkiri/security/filters/JwtAuthenticationFilter.java
src/main/java/com/app/kkiri/security/handlers/CustomAccessDeniedHandler.java
src/main/java/com/app/kkiri/security/handlers/OAuth2AuthenticationFailureHandler.java
src/main/java/com/app/kkiri/security/handlers/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/app/kkiri/security/utils/JwtTokenProvider.java
src/main/resources/application.yml

- 토큰을 이용한 인증 시 500 에러를 해결했습니다.
- 응답시 body 에 담긴 문자열이 ??? 로 보이는 현상을 해결했습니다.

📝fix : 토큰을 통한 인증 시 발생하는 500 에러와 응답 body 에 담긴 문자열이 ??? 로 보이는 문제를 해결함

---

src/main/java/com/app/kkiri/security/SecurityConfig.java
src/main/java/com/app/kkiri/security/filters/JwtExceptionFilter.java

- 토큰을 사용한 인증 시 발생하는 에러를 잡기 위해 새로운 JwtException 필터를 생성하고 적용하였습니다.

📝fix : 토큰을 통한 인증 시 발생하는 500 에러를 해결함

---

src/main/java/com/app/kkiri/controller/TestController.java
src/main/resources/application.yml

- 프론트 엔드 팀의 요청으로 클라이언트의 리다이렉트 URI 를 변경했습니다.

📝fix : 클라이언트의 리다이렉트 URI 를 변경했음

---

.gitignore
build.gradle
src/main/java/com/app/kkiri/controller/TestController.java
src/main/java/com/app/kkiri/service/FileService.java

- S3EncryptionClient 를 사용하여 암호화된 S3 객체를 복호화해서 리턴하는 기능을 개발했습니다.

🌈feat : S3에 저장된 암호화 된 파일을 복호화하는 기능을 개발함

---

build.gradle
src/main/java/com/app/kkiri/S3Config.java
src/main/java/com/app/kkiri/service/FileService.java

- 기존 org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE 의존성을 삭제하고 com.amazonaws:aws-java-sdk-s3:1.12.586 의존성을 추가하였습니다.

📝fix : S3 객체를 복호화 하는 서비스에서 발생하는 에러를 해결하는 중

---

.gitignore
src/main/java/com/app/kkiri/controller/SpaceController.java
src/main/java/com/app/kkiri/controller/TestController.java
src/main/java/com/app/kkiri/service/FileService.java
src/main/java/com/app/kkiri/service/SpaceService.java

- 민감한 정보가 포함된 application.yml 파일을 GitHub 에 업로드하지 않도록 .gitignore 파일에 *.yml 을 추가했습니다.

📚docs : .gitignore 파일에 .yml 파일을 추가함

---

build.gradle
src/main/java/com/app/kkiri/S3Config.java
src/main/java/com/app/kkiri/controller/PostController.java
src/main/java/com/app/kkiri/controller/SpaceController.java
src/main/java/com/app/kkiri/controller/TestController.java
src/main/java/com/app/kkiri/service/FileService.java
src/main/java/com/app/kkiri/service/PostService.java
src/main/java/com/app/kkiri/service/SpaceService.java

- S3 버킷의 암호화 설정을 변경했습니다.
- Amazon SDK for Java 를 1.x 버전에서 2.x 버전으로 변경했습니다.

📝fix : URL 를 통해 이미지 파일에 접근할 수 없었던 에러를 해결 중임

---

src/main/java/com/app/kkiri/controller/PostController.java
src/main/java/com/app/kkiri/controller/SpaceController.java

없음.
- 응답 코드가 401일 경우 기존 헤더에 새로 생성된 리소스에 대한 정보를 담아서 보냈지만, 프론트 팀에서 코드를 수정해야하는 번거로움이 있어, 새로 생성된 리소스를 바디에 담아서 보내는 것으로 코드를 변경했습니다.
없음.

🚧refactor : Http 응답 코드가 401 일 경우 응답 내용을 변경함

---

src/main/java/com/app/kkiri/security/jwt/JwtTokenProvider.java

없음.
- 요청의 헤더에 담긴 액세스 토큰으로부터 사용자 고유번호를 추출하는 로직에서 JwtException 이 발생하였지만 이를 처리하는 로직이 없어 새로 작성하였습니다.
없음.

📝fix : 요청의 헤더에 담긴 액세스 토큰으로부터 사용자 고유번호를 추출하는 로직에서 발생하는 예외를 처리함

---

src/main/java/com/app/kkiri/controller/SpaceController.java
src/main/java/com/app/kkiri/security/jwt/JwtTokenProvider.java

없음.
- 요청의 헤더에 담긴 액세스 토큰으로부터 사용자 고유번호를 추출하는 로직에서 발생하는 예외 상황을 토큰이 만료된 경우와 올바르지 않은 형식의 토큰인 경우로 세분화 하여 처리했습니다.
없음.

📝fix : 요청의 헤더에 담긴 액세스 토큰으로부터 사용자 고유번호를 추출하는 로직에서 발생하는 예외 처리를 세분화 함

---

src/main/java/com/app/kkiri/controller/SpaceController.java
src/main/java/com/app/kkiri/controller/UserController.java

없음.
- 액세스 토큰 재발급 API 의 메소드를 기존 PATCH 에서 GET 으로 변경했습니다.
없음.

🚧refactor : 액세스 토큰 재발급 API 의 메소드를 기존 PATCH 에서 GET 으로 변경함

---

src/main/java/com/app/kkiri/controller/SpaceController.java
src/main/java/com/app/kkiri/domain/dto/TagDTO.java
src/main/java/com/app/kkiri/domain/vo/TagVO.java
src/main/java/com/app/kkiri/service/SpaceService.java
src/main/resources/mapper/TagsMapper.xml

없음.
- 스페이스 생성 시 기본 태그를 생성하는 로직을 구현했습니다.
없음.

🌈feat : 스페이스 생성 시 기본 태그 생성 로직 구현

---

src/main/java/com/app/kkiri/security/SecurityConfig.java

없음.
- 기존 CORS 허용 origin 에 https://localhost:3000 를 추가했습니다.
없음.

📝fix : 게시글 필터 조회 API CORS 에러를 수정중임

---

.idea/modules/kkiri.main.iml
build.gradle
src/main/java/com/app/kkiri/controller/CommentController.java
src/main/java/com/app/kkiri/global/config/S3Config.java
src/main/java/com/app/kkiri/global/exception/ExceptionCode.java
src/main/java/com/app/kkiri/security/SecurityConfig.java
src/main/java/com/app/kkiri/service/FileService.java

<Pull Request>
#53 
- 로컬에서 S3 버킷을 이용한 파일 업로드, 파일 URL 조회, 파일 삭제가 동작하지 않았었는데, 사용자의 액세스 토큰과 시크릿 토큰을 사용하여 S3 버킷을 연결하였더니 동작하게 되었습니다.
- application.yml 에 업로드 가능한 최대 파일의 크기를 10MB 로 설정하였지만 적용되지 않았습니다. 하지만 위의 방법으로 S3 버킷을 연결하니 자연스럽게 적용되었습니다.
없음.

📝fix : 로컬에서 S3 버킷을 이용한 파일 업로드, 파일 URL 조회, 파일 삭제가 동작하지 않았던 오류를 해결함.

---

src/main/java/com/app/kkiri/global/config/RestTemplateConfiguration.java

없음.
- RestTemplate 설정에 TimeOut 시간을 2배 연장하였습니다.
없음.

📝fix : 데이터베이스 연결시 TimeOut 에러 해결 중
